### ISSUE TITLE
mode wrap broken in #168

### ISSUE THREAD

**Issue by PeoB** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#172]
We end up with 
```
template.expression is not a function
    at wrapTemplate (/*/node_modules/babel-plugin-transform-react-remove-prop-types
```

From here https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/pull/168/files#diff-1fdf421c05c1140f6d71444ea2b27638R157
When we are using `mode: wrap` for our code-base
Installing `0.4.19` works as a workaround

/cc @oliviertassinari

**Comment by oliviertassinari** [comment]
@PeoB I have upgraded the dependency to v0.4.20 in https://github.com/mui-org/material-ui/pull/13540 without any issue. Do you have a reproduction example?
